# Railway Configuration for TrueCivic API
# This deploys the FastAPI backend service

[build]
builder = "DOCKERFILE"
dockerfilePath = "api.dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
timeout = 30
interval = 30
