# Railway Configuration for TrueCivic Frontend
# This deploys the Next.js frontend service
# 
# To use this configuration:
# 1. Create a new Railway service
# 2. Name it "truecivic-frontend"
# 3. In service settings, set "Railway Config File Path" to: railway-frontend.toml

[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm ci --include=dev && npm run build"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "cd frontend && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/"
timeout = 100
interval = 30

# Environment variables needed:
# NEXT_PUBLIC_API_URL - Set to your Railway API service URL (e.g., https://truecivic-api.up.railway.app)
