"""initial schema with bills, politicians, fetch_logs

Revision ID: 7bd692ce137c
Revises: 
Create Date: 2025-10-17 19:00:55.059802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd692ce137c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('parliament', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_fr', sa.Text(), nullable=True),
    sa.Column('short_title_en', sa.Text(), nullable=True),
    sa.Column('short_title_fr', sa.Text(), nullable=True),
    sa.Column('sponsor_politician_id', sa.Integer(), nullable=True),
    sa.Column('sponsor_politician_name', sa.String(length=200), nullable=True),
    sa.Column('introduced_date', sa.DateTime(), nullable=True),
    sa.Column('law_status', sa.String(length=100), nullable=True),
    sa.Column('legisinfo_id', sa.Integer(), nullable=True),
    sa.Column('legisinfo_status', sa.String(length=200), nullable=True),
    sa.Column('legisinfo_summary_en', sa.Text(), nullable=True),
    sa.Column('legisinfo_summary_fr', sa.Text(), nullable=True),
    sa.Column('subject_tags', sa.JSON(), nullable=True),
    sa.Column('committee_studies', sa.JSON(), nullable=True),
    sa.Column('royal_assent_date', sa.DateTime(), nullable=True),
    sa.Column('royal_assent_chapter', sa.String(length=20), nullable=True),
    sa.Column('related_bill_numbers', sa.JSON(), nullable=True),
    sa.Column('source_openparliament', sa.Boolean(), nullable=False),
    sa.Column('source_legisinfo', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('parliament > 0', name='ck_parliament_positive'),
    sa.CheckConstraint('session > 0', name='ck_session_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction', 'parliament', 'session', 'number', name='uq_bill_natural_key')
    )
    op.create_index('idx_bill_fetch_timestamp', 'bills', ['last_fetched_at', 'parliament', 'session'], unique=False)
    op.create_index('idx_bill_parliament_session', 'bills', ['parliament', 'session', 'introduced_date'], unique=False)
    op.create_index(op.f('ix_bills_introduced_date'), 'bills', ['introduced_date'], unique=False)
    op.create_index(op.f('ix_bills_jurisdiction'), 'bills', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_bills_last_fetched_at'), 'bills', ['last_fetched_at'], unique=False)
    op.create_index(op.f('ix_bills_legisinfo_id'), 'bills', ['legisinfo_id'], unique=True)
    op.create_index(op.f('ix_bills_number'), 'bills', ['number'], unique=False)
    op.create_index(op.f('ix_bills_parliament'), 'bills', ['parliament'], unique=False)
    op.create_index(op.f('ix_bills_royal_assent_date'), 'bills', ['royal_assent_date'], unique=False)
    op.create_index(op.f('ix_bills_session'), 'bills', ['session'], unique=False)
    op.create_index(op.f('ix_bills_sponsor_politician_id'), 'bills', ['sponsor_politician_id'], unique=False)
    op.create_table('fetch_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('records_attempted', sa.Integer(), nullable=False),
    sa.Column('records_succeeded', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('fetch_params', sa.JSON(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fetch_log_created', 'fetch_logs', ['created_at'], unique=False)
    op.create_index('idx_fetch_log_source_status', 'fetch_logs', ['source', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_fetch_logs_created_at'), 'fetch_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fetch_logs_source'), 'fetch_logs', ['source'], unique=False)
    op.create_index(op.f('ix_fetch_logs_status'), 'fetch_logs', ['status'], unique=False)
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=True),
    sa.Column('family_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('current_party', sa.String(length=100), nullable=True),
    sa.Column('current_riding', sa.String(length=200), nullable=True),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('memberships', sa.JSON(), nullable=True),
    sa.Column('parl_mp_id', sa.String(length=50), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parl_mp_id')
    )
    op.create_index('idx_politician_fetch_timestamp', 'politicians', ['last_fetched_at'], unique=False)
    op.create_index('idx_politician_party_riding', 'politicians', ['current_party', 'current_riding'], unique=False)
    op.create_index(op.f('ix_politicians_current_party'), 'politicians', ['current_party'], unique=False)
    op.create_index(op.f('ix_politicians_current_riding'), 'politicians', ['current_riding'], unique=False)
    op.create_index(op.f('ix_politicians_last_fetched_at'), 'politicians', ['last_fetched_at'], unique=False)
    op.create_index(op.f('ix_politicians_name'), 'politicians', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_politicians_name'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_last_fetched_at'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_current_riding'), table_name='politicians')
    op.drop_index(op.f('ix_politicians_current_party'), table_name='politicians')
    op.drop_index('idx_politician_party_riding', table_name='politicians')
    op.drop_index('idx_politician_fetch_timestamp', table_name='politicians')
    op.drop_table('politicians')
    op.drop_index(op.f('ix_fetch_logs_status'), table_name='fetch_logs')
    op.drop_index(op.f('ix_fetch_logs_source'), table_name='fetch_logs')
    op.drop_index(op.f('ix_fetch_logs_created_at'), table_name='fetch_logs')
    op.drop_index('idx_fetch_log_source_status', table_name='fetch_logs')
    op.drop_index('idx_fetch_log_created', table_name='fetch_logs')
    op.drop_table('fetch_logs')
    op.drop_index(op.f('ix_bills_sponsor_politician_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_session'), table_name='bills')
    op.drop_index(op.f('ix_bills_royal_assent_date'), table_name='bills')
    op.drop_index(op.f('ix_bills_parliament'), table_name='bills')
    op.drop_index(op.f('ix_bills_number'), table_name='bills')
    op.drop_index(op.f('ix_bills_legisinfo_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_last_fetched_at'), table_name='bills')
    op.drop_index(op.f('ix_bills_jurisdiction'), table_name='bills')
    op.drop_index(op.f('ix_bills_introduced_date'), table_name='bills')
    op.drop_index('idx_bill_parliament_session', table_name='bills')
    op.drop_index('idx_bill_fetch_timestamp', table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
